import './globals.css';
import styles from './layout.module.css';
import {Noto_Sans} from 'next/font/google';
import {Header} from '../layout/Header/Header';
import {Sidebar} from '../layout/Sidebar/Sidebar';
import {Footer} from '../layout/Footer/Footer';
import {IAppContext, AppContextProvider} from '../context/app.context';
import axios from 'axios';
import { MenuItem } from '@/interfaces/menu.interface';


const nano = Noto_Sans({
  subsets: ['cyrillic', 'cyrillic-ext', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-nano',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const firstCategory = 0;
  const {data: menu} = await axios.post<MenuItem[]>(process.env.NEXT_PUBLIC_DOMAIN + '/api/top-page/find', {
    firstCategory
  });

  return (
    <html lang="en">
    <AppContextProvider menu={menu} firstCategory={firstCategory}>
      <body className={nano.className}><div className={styles.wrapper}>
        <Header className={styles.header}/>
            <Sidebar className={styles.sidebar}/>
            <div className={styles.body}>
                {children}
            </div>
        <Footer className={styles.footer}/>
        </div>
      </body>
    </AppContextProvider>
    </html>
  );
}
