import './globals.css';
import {Noto_Sans} from 'next/font/google';

const nano = Noto_Sans({
  subsets: ['cyrillic', 'cyrillic-ext', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-nano',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={nano.className}>{children}</body>
    </html>
  );
}
